version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: HyperX2025!*
      POSTGRES_DB: hyperxconvert
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-net

  backend:
    build:
      context: ./backend
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hyperxconvert
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: HyperX2025!*
    networks:
      - spring-net

volumes:
  pgdata:

networks:
  spring-net:
