# Note:
# - Run for overriding: docker compose -f docker-compose.yml up -d
# - Docker Compose sẽ tự động tạo network mặc định cho tất cả services trong file.
# - Vì chỉ có 1 service (backend), không cần định nghĩa networks

version: '3.8'
services:
  backend:
    image: hyperxconvert/springboot-app:latest  # Ban đầu để tag là 'latest', script sẽ thay bằng tag mới
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # AWS_ chỉ khả dụng khi có file .env, và chỉ dùng khi test profile prod ở local
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_REGION: ${AWS_REGION:-ap-southeast-1}
