# Note:
# - Run for overriding: docker compose -f docker-compose.yml up -d
# - Docker Compose sẽ tự động tạo network mặc định cho tất cả services trong file.
# - Vì chỉ có 1 service (backend), không cần định nghĩa networks

version: '3.8'

services:
  backend:
    build:
      context: ./
    container_name: springboot-app
    ports:
      - "8080:8080"
