spring:
  config:
    activate:
      on-profile: staging # -Dspring.profiles.active=staging
  datasource:
    url: jdbc:postgresql://hyperxconvert-db.crme0kq4arx0.ap-southeast-1.rds.amazonaws.com:5432/hyperxconvert

aws:
  s3:
    bucket: hyperxconvert-staging
  sqs:
    upload-queue: https://sqs.ap-southeast-1.amazonaws.com/{account-id}/upload-queue-staging
    convert-queue: https://sqs.ap-southeast-1.amazonaws.com/{account-id}/convert-queue-staging
    dlq-upload-queue: https://sqs.ap-southeast-1.amazonaws.com/{account-id}/dlq-upload-queue-staging
    dlq-convert-queue: https://sqs.ap-southeast-1.amazonaws.com/{account-id}/dlq-convert-queue-staging
  ses:
    from-address: no-reply-staging@hyperxconvert.com

app:
  upload:
    max-daily-uploads: 5

logging:
  file:
    name: /home/ec2-user/hyperxconvert-backend.log