spring:
  application:
    name: hyperxconvert-backend
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  messages:
    basename: messages_vi
    encoding: UTF-8

server:
  port: 8080

app:
  upload:
    max-daily-uploads: 5
    presigned-url-expiry: PT24H  # 24 hours

conversion:
  pdf2docx-cmd: "pdf2docx"
  sharp-cmd: "sharp"
  ffmpeg-cmd: "ffmpeg"
  ghostscript-cmd: "gs"
