spring.application.name=hyperxconvert-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/hyperxconvert
spring.datasource.username=postgres
spring.datasource.password=HyperX2025!*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

aws.region=ap-southeast-1
aws.s3.bucket=hyperxconvert
aws.sqs.upload-queue=upload-queue
aws.sqs.convert-queue=convert-queue