spring:
  application:
    name: hyperxconvert-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  messages:
    basename: messages
    encoding: UTF-8

logging: # Tắt log cảnh báo của Hibernate
  level:
    org.hibernate.orm.connections.pooling: WARN
    org.hibernate: WARN
    org.springframework.orm.jpa: WARN

server:
  port: 8080

conversion:
  pdf2docx-cmd: "pdf2docx"
  sharp-cmd: "sharp"
  ffmpeg-cmd: "ffmpeg"
  qpdf-cmd: "qpdf"
