spring:
  config:
    activate:
      on-profile: dev # -Dspring.profiles.active=dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hyperxconvert
#    username: extended
#    password: extended
#    driver-class-name: extended

aws:
#  region: extended
  s3:
    bucket: hyperxconvert-staging
  sqs:
    upload-queue: https://sqs.ap-southeast-1.amazonaws.com/037195638912/upload-queue-staging
    convert-queue: https://sqs.ap-southeast-1.amazonaws.com/037195638912/convert-queue-staging
    dlq-upload-queue: https://sqs.ap-southeast-1.amazonaws.com/037195638912/dlq-upload-queue-staging
    dlq-convert-queue: https://sqs.ap-southeast-1.amazonaws.com/037195638912/dlq-convert-queue-staging

app:
  upload:
    max-daily-uploads: 1000